# Generated by Django 3.2.20 on 2023-08-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slot',
            field=models.CharField(choices=[('', 'Select Course'), ('DigitalMarketing', 'Digital Marketing'), ('GraphicsDesigning', 'Graphics Designing'), ('WebDevelopment', 'Web Development')], max_length=254),
        ),
    ]
