# Generated by Django 3.2.20 on 2023-08-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_date_contact_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='slot',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=12, max_length=120),
            preserve_default=False,
        ),
    ]
