# Generated by Django 3.2.20 on 2023-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20230814_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='img_branches')),
                ('select_1', models.BooleanField(choices=[('healthy', 'Healthy'), ('worksout', 'Works Out'), ('fitness', 'Fitness')], default=False)),
                ('select_2', models.BooleanField(choices=[('healthy', 'Healthy'), ('worksout', 'Works Out'), ('fitness', 'Fitness')], default=False)),
                ('select_3', models.BooleanField(choices=[('healthy', 'Healthy'), ('worksout', 'Works Out'), ('fitness', 'Fitness')], default=False)),
            ],
        ),
    ]
