# Generated by Django 3.2.20 on 2023-08-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20230815_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='cat',
            field=models.CharField(choices=[(0, 'Healthy Food'), (1, 'Workout'), (2, 'Fitness')], default=1, max_length=10),
        ),
    ]
