# Generated by Django 3.2.20 on 2023-08-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_galleryimages_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='cat',
            field=models.CharField(choices=[('Healthy Food', 'Healthy Food'), ('Workout', 'Workout'), ('Fitness', 'Fitness')], default='Healthy Food', max_length=20),
        ),
    ]
