# Generated by Django 3.2.20 on 2023-08-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20230817_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
