# Generated by Django 3.2.20 on 2023-08-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimages',
            name='fitness',
        ),
        migrations.RemoveField(
            model_name='galleryimages',
            name='healthy',
        ),
        migrations.RemoveField(
            model_name='galleryimages',
            name='works_out',
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='cat',
            field=models.CharField(choices=[('Healthy Food', 'Healthy Food'), ('Workout', 'Workout'), ('Fitness', 'Fitness')], default='Healthy Food', max_length=20),
        ),
    ]
