# Generated by Django 3.2.20 on 2023-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20230823_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=12, max_length=120),
            preserve_default=False,
        ),
    ]
