# Generated by Django 3.2.20 on 2023-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_gallery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spanclassname', models.CharField(choices=[('flaticon-heart', 'Heart Icon'), ('flaticon-yoga', 'Yoga Icon'), ('flaticon-sneakers', 'Sneakers Icon')], max_length=20)),
            ],
        ),
    ]
