# Generated by Django 3.2.20 on 2023-08-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_business_sector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business_Sector',
        ),
    ]
