# Generated by Django 3.2.20 on 2023-09-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_bussiness_sector'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Indexform',
        ),
    ]
